### PR TITLE
Profile validation

### PR DESCRIPTION
**Pull request by bartbutenaers**
Hey Flurin (@cflurin),

As promised here is my custom validation function to validate the entire profile. 

1. The first non-empty time should be 00:00

   image

1. The last non-empty time should be 23:59

   image

1. Time should be non-empty when the temperature is non-empty:

   image

1. Temperature should be non-empty when the time is non-empty:

   image

1. Time cannot be located before the previous time:

   image

1. Time cannot be equal to the previous time (independent of the temperature values):

   image

1. Pattern check on both time and temperature fields (identical as in your original version), but this is only useful for temperature fields (since the time widgets autocorrect invalid input, at least in Chrome):

   image

Some remarks:
+ I don't mark empty lines (in front and in between) as invalid.  Don't know if that is what you want?
+ The validations are executed automatically at each change, so users will see the problems immediately

Hope to hear from you soon!
Bart

### CODE REVIEW

**Comment by bartbutenaers** [comment]
Flurin,

Seems I was a bit too soon submitting this pull request.
I now (accidentally) saw that - when flow editor browser screen is refreshed - following errors occur:

image

This occurs a.o. at this line:
```
if ($('#node-config-input-temp' + index)[0].value) {
```
Because the node-config-input-tempx does only exist when the validations are executed when the config screen is open.  But now the validations are executed at startup (without config screen), so the screen elements are undefined.

So I '_think_' the validation function should use ```this.tempx``` when ```$('#node-config-input-tempx')``` is empty.  I will have to update this pull request ...

**Comment by bartbutenaers** [comment]
The validation at startup has been fixed.  I have introduced a ```getValue``` function that tries to get the value from the screen.  If no screen element available, it gets the value from 'this' Javascript object. 

Caution: I needed to pass 'this' to getValue, because at startup the 'this' will be the global Window from Node-RED (instead of 'this' node)...

**Comment by cflurin** [comment]
Hi Bart,

1. It seems that you used v0.5.0 to fork for this PR, you should take the latest master (commit 65, Nov 21, 2018).

2. Please, test your code with the getProfile example, this is a valid profile but I get an error.
https://github.com/cflurin/node-red-contrib-ramp-thermostat/wiki/getProfile

Edit:

6. ... is valid > It's a small change (line 228-229):
```
// Invalid time: when current time is before the previous non-empty time
if (minutes < previousMinutes) {
```

**Comment by bartbutenaers** [comment]
Hello Flurin (@cflurin),

+ I have synced my fork to bring it up to date with your latest master branch.  How stupid of me ...
+ Your getProfile example indeed gives an error, but when open the config node I see this:

   image

   Seems to me related to the next point...  Question 1: Am I correct that this is not a separate issue, when the next point is solved?
+ You want ```<``` instead of ```<=```.  Question 2:  shouldn't two equal timestamps trigger an error?  Or does the above screenshot mean perhaps that you go at 12:00 suddenly from 20,5 to 19?  Is that allowed?  Question 3: If so, I assume I should trigger an error when both timestamp AND temperature are identical?

Thanks for reviewing !!
Bart

**Comment by cflurin** [comment]
>   Seems to me related to the next point...  Question 1: Am I correct that this is not a separate issue, when the next point is solved?
> * You want `<` instead of `<=`.  Question 2:  shouldn't two equal timestamps trigger an error?  Or does the above screenshot mean perhaps that you go at 12:00 suddenly from 20,5 to 19?  Is that allowed?  Question 3: If so, I assume I should trigger an error when both timestamp AND temperature are identical?
> 

Hi Bart,

1. Right

2.  `<` is Ok, two equal time values are allowed.

3. No, it isn't necessary and this might be useful.

You probably would better understand it if you have a look a the `getState` function (and read the wikipedia article about the programmable thermostat).

You don't need to understand all the code just these lines:

```
      if (current_mins < point_mins || point_mins === 1439) {
        gradient = (point_target - pre_target) / (point_mins - pre_mins);
        target = pre_target + (gradient * (current_mins - pre_mins));        
        break;
      }
```

Please, just try to use the ramp-thermostat in a practical use case:

1. Read the room temperature (e.g. using a ds18b20 sensor + the  `rpi-ds18b20` node with a Raspberry Pi) and wire it to the ramp-thermostat input.
2. Wire the ramp-thermostat output 1 to an actuator to turn on/off the heating.

**Comment by cflurin** [comment]
Hi Bart,
PR merged, however there is still an issue:
Restarting with the new html version (including profile validation) the node shows a red triangle:

Could you please have a look at your PR. Thanks.

living

Profile:

livingprofile

flow.json > profile standard

```
    {
        "id": "2f01ab8d.e70144",
        "type": "profile",
        "z": "",
        "name": "standard",
        "time1": "00:00",
        "temp1": "18",
        "time2": "03:00",
        "temp2": "18",
        "time3": "06:00",
        "temp3": "20",
        "time4": "11:00",
        "temp4": "20",
        "time5": "11:30",
        "temp5": "18",
        "time6": "13:30",
        "temp6": "18",
        "time7": "14:00",
        "temp7": "20",
        "time8": "19:00",
        "temp8": "20",
        "time9": "20:00",
        "temp9": "18",
        "time10": "24:00",
        "temp10": "18"
    },
```

**Comment by bartbutenaers** [comment]
Hi Flurin,

When I import the flow (containing **24:00**) the validators will be executed:

image

And of course I give an error when the last time is not 23:59.  
And (only) when you open the config screen, it will execute **oneditprepare** behind the scenes (where you convert the 24:00 to 23:59).  But your migration code in oneditprepare will not be executed in this case ...

And I don't want to allow the 24:00 as a valid value...
And I don't think Node-RED allows me to do some conversion after loading.  Will ask it on the forum anyway tonight.

There might be a workaround.  When the validator is executed (without opening the config screen) the same timestamp in the node will also be 24:00
image
This way I know that your migration (in oneditprepare) has not been executed yet (since you have not opened the config screen yet), so I that case I could allow 24:00 to be a valid value...

Is that OK for you ?
Bart

**Comment by bartbutenaers** [comment]
@cflurin,
Summarized I would allow ```this.tempx``` to be 24:00, but the screen field ```$('#node-config-input-tempx')``` is not allowed to be 24:00.  Because the latter one is a value that the user has now entered on the screen, and we don't allow that value anymore...

**Comment by cflurin** [comment]
Hi Bart,

In the meantime I tried this modification, it solves the problem:

line 249 ...

```
                if (last && (value != "23:59" && value != "24:00")) {
                    return false;
                }
```

**Comment by bartbutenaers** [comment]
Flurin,

That solution seems indeed to be sufficient.  Thought that a user would be able this way to enter 24:00 in the config screen, however the time-widgets don't allow 24:00 to be entered ...
So for me this looks good!

Thanks for the nice cooperation!
Bart

**Comment by cflurin** [comment]
Hi Bart,

I've uploaded the fix.

One question:

The function `validateSetPoints` has 2 arguments:
```
    function validateSetPoints(property, value) {
``` 

but it is called with 3 arguments:

```
time1: {value:'', validate:function(v) { return validateSetPoints.call(this,"time1",v) }},
temp1: {value:'', validate:function(v) { return validateSetPoints.call(this,"temp1",v) }},
```

I think, it should also work this way:
```
time1:  {value:'', validate:function(v) { return validateSetPoints.call("time1" ,v) }},
temp1:  {value:'', validate:function(v) { return validateSetPoints.call("temp1" ,v) }},
```

Is there a reason I don't see to add `this` ?

**Comment by cflurin** [comment]
... ignore my last post. I didn't notice that it's a `.call()`

**Pull request merged**
